from abc import ABC, abstractmethod
from typing import Optional, List, Dict, Any

class IUserRepository(ABC):
    @abstractmethod
    async def get_by_email(self, email: str) -> Optional[Dict[str, Any]]: ...
    @abstractmethod
    async def get_by_id(self, user_id: str) -> Optional[Dict[str, Any]]: ...
    @abstractmethod
    async def list_users(self) -> List[Dict[str, Any]]: ...

class IProductRepository(ABC):
    @abstractmethod
    async def get_by_id(self, product_id: str) -> Optional[Dict[str, Any]]: ...
    @abstractmethod
    async def get_by_fingerprint(self, fingerprint_sha256: str) -> Optional[Dict[str, Any]]: ...
    @abstractmethod
    async def list_products(self) -> List[Dict[str, Any]]: ...
    @abstractmethod
    async def create_or_update(self, product_data: Dict[str, Any]) -> Dict[str, Any]: ...
    @abstractmethod
    async def add_label_version(self, label_version_data: Dict[str, Any]) -> Dict[str, Any]: ...
    @abstractmethod
    async def get_label_versions(self, product_id: str) -> List[Dict[str, Any]]: ...

class IInspectionRepository(ABC):
    @abstractmethod
    async def create(self, inspection_data: Dict[str, Any]) -> Dict[str, Any]: ...
    @abstractmethod
    async def get_by_id(self, inspection_id: str) -> Optional[Dict[str, Any]]: ...
    @abstractmethod
    async def update(self, inspection_id: str, updates: Dict[str, Any]) -> Optional[Dict[str, Any]]: ...
    @abstractmethod
    async def list_inspections(self, inspector_id: Optional[str] = None, status: Optional[str] = None, query: Optional[str] = None) -> List[Dict[str, Any]]: ...
    @abstractmethod
    async def add_image(self, inspection_id: str, image_data: Dict[str, Any]) -> Dict[str, Any]: ...
    @abstractmethod
    async def delete_image(self, inspection_id: str, image_id: str) -> bool: ...
    @abstractmethod
    async def save_declarations(self, inspection_id: str, declarations: List[Dict[str, Any]]) -> List[Dict[str, Any]]: ...
    @abstractmethod
    async def update_declaration(self, declaration_id: str, updates: Dict[str, Any]) -> Optional[Dict[str, Any]]: ...
    @abstractmethod
    async def save_compliance_results(self, inspection_id: str, checks: List[Dict[str, Any]], violations: List[Dict[str, Any]]) -> None: ...
    @abstractmethod
    async def update_finding(self, finding_id: str, updates: Dict[str, Any]) -> Optional[Dict[str, Any]]: ...
    @abstractmethod
    async def finalize_inspection(self, inspection_id: str, snapshot_data: Dict[str, Any]) -> Dict[str, Any]: ...

class IRuleRepository(ABC):
    @abstractmethod
    async def list_rules(self, category: Optional[str] = None, active_only: bool = True) -> List[Dict[str, Any]]: ...
    @abstractmethod
    async def get_rule_by_id(self, rule_id: str) -> Optional[Dict[str, Any]]: ...
    @abstractmethod
    async def get_active_versions_for_date(self, inspection_date_iso: str) -> List[Dict[str, Any]]: ...
    @abstractmethod
    async def create_rule(self, rule_data: Dict[str, Any]) -> Dict[str, Any]: ...
    @abstractmethod
    async def create_version(self, rule_id: str, version_data: Dict[str, Any]) -> Dict[str, Any]: ...
    @abstractmethod
    async def get_rule_coverage(self) -> List[Dict[str, Any]]: ...

class IReportRepository(ABC):
    @abstractmethod
    async def save_report_metadata(self, report_data: Dict[str, Any]) -> Dict[str, Any]: ...
    @abstractmethod
    async def get_report_by_inspection_id(self, inspection_id: str) -> Optional[Dict[str, Any]]: ...

class IAuditLogRepository(ABC):
    @abstractmethod
    async def append_log(self, log_entry: Dict[str, Any]) -> Dict[str, Any]: ...
    @abstractmethod
    async def list_logs(self, limit: int = 100) -> List[Dict[str, Any]]: ...
